In [4]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np                                             #넘파이:벡터행렬연산, 수학함수계산
from scipy import stats                                        #싸이파이:수치해석, stats:확률분포

In [15]:
dft = pd.read_csv('../Data/Default.csv')
dft.head()

default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [20]:
# 범주형을 0,1 로 변환 후, 새로운 피쳐로 저장
# income 피처는 덮어쓰기로 저장
dft['studentYes'] = (dft['student']=='Yes').astype(np.int)      #또는 np.multiply(dft['student']=='Yes',1)
dft['defaultYes'] = (dft['default']=='Yes').astype(np.int)      #또는 np.multiply(dft['default']=='Yes',1)
dft['income'] = dft['income']/1000                              #income in tho. dollars
dft.head()

/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32

default student      balance    income  studentYes  defaultYes
0      No      No   729.526495  0.044362           0           0
1      No     Yes   817.180407  0.012106           1           0
2      No      No  1073.549164  0.031767           0           0
3      No      No   529.250605  0.035704           0           0
4      No      No   785.655883  0.038463           0           0

In [17]:
# glm 함수는 일반화선형모형, 회귀분석, 로지스틱 회귀분석을 포함
# 회귀분석은 정규분포 혹은 가우시안 분포
# 로지스틱은 베르누이분포 바이노미알 분포
# glm 은 포아성분포, 감마분포

import statsmodels.api as sm                                    #통계모형  
import statsmodels.formula.api as smf # 로지스틱 패키지

In [58]:
# formula: 왼쩍이 반응변수, 오른쪽이 설명변수
# 로그오즈를 선형변수
# 절편은 따로 명시 안 해도 포함됨, 포함하고 싶으면 -1을 ''안에 포함
# 만약 ~ 뒤에 1 쓰면 설명변수 없는 상수함수가 됨
# 로지스틱일 땐 family 로 binomial 을 명시해줘야 함, 안 쓰면 선형회귀분석됨
# fit(): 모형적합

fit1 = smf.glm(formula = 'defaultYes~studentYes', data=dft, family=sm.families.Binomial()).fit()

# 모형적합의 결과
fit1.summary()

# Observations: 관측개수
# Df: 자유도

#n 개의 관측치가 있으면 전체 자유도는 n
#모형을 표현하는 모수의 갯수가 모형의 자유도
#n 에서 모형의 자유도를 뺀게 잔차의 자유도
#때로는 절편을 제외한 것을 모형의 자유도로 보기도 함

# Log-Likelihood: 가능도에 로그를 취한 것, 적합된 모형의 로그 가능도

# 아래 추론값이 나와 이로 로그오즈를 구하고
# 로그오즈로 확률함수를 구한다

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:             defaultYes   No. Observations:                10000
Model:                            GLM   Df Residuals:                     9998
Model Family:                Binomial   Df Model:                            1
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -1454.3
Date:                Wed, 17 Mar 2021   Deviance:                       2908.7
Time:                        16:22:50   Pearson chi2:                 1.00e+04
No. Iterations:                     6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -3.5041      0.071    -49.554      0.000      -3.643      -3.366
studentYes     0.4049      0.115      3.520      0.000       0.179       0.630
==============================================================================
"""

In [59]:
# 설명변수가 달라짐

fit2 = smf.glm(formula = 'defaultYes~balance', data=dft, family=sm.families.Binomial()).fit()
fit2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:             defaultYes   No. Observations:                10000
Model:                            GLM   Df Residuals:                     9998
Model Family:                Binomial   Df Model:                            1
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -798.23
Date:                Wed, 17 Mar 2021   Deviance:                       1596.5
Time:                        16:34:52   Pearson chi2:                 7.15e+03
No. Iterations:                     9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -10.6513      0.361    -29.491      0.000     -11.359      -9.943
balance        0.0055      0.000     24.952      0.000       0.005       0.006
==============================================================================
"""

In [23]:
dir(fit1)
conf = fit1.conf_int()
conf['coef'] = fit1.params
conf.columns = ['2.5%', '97.5%', 'coef']
print(conf)

                2.5%     97.5%      coef
Intercept  -3.642723 -3.365533 -3.504128
studentYes  0.179454  0.630320  0.404887


In [24]:
conf_OR=np.exp(conf)
conf_OR.columns = ['2.5%', '97.5%', 'Odds Ratio']
print(conf_OR)

                2.5%     97.5%  Odds Ratio
Intercept   0.026181  0.034544    0.030073
studentYes  1.196564  1.878211    1.499133


In [25]:
fit3 = smf.glm(formula = 'defaultYes~balance+income+studentYes', data=dft, family=sm.families.Binomial()).fit()
fit3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:             defaultYes   No. Observations:                10000
Model:                            GLM   Df Residuals:                     9996
Model Family:                Binomial   Df Model:                            3
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -785.77
Date:                Wed, 17 Mar 2021   Deviance:                       1571.5
Time:                        16:11:35   Pearson chi2:                 7.00e+03
No. Iterations:                     9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -10.8690      0.492    -22.079      0.000     -11.834      -9.904
balance        0.0057      0.000     24.737      0.000       0.005       0.006
income         3.0335      8.203      0.370      0.712     -13.044      19.111
studentYes    -0.6468      0.236     -2.738      0.006      -1.110      -0.184
==============================================================================
"""

In [26]:
dir(fit3)
conf = fit3.conf_int()
conf['coef'] = fit3.params
conf['se'] = fit3.bse
conf.columns = ['2.5%', '97.5%', 'coef', 'se']
print(conf)

                 2.5%      97.5%       coef        se
Intercept  -11.833882  -9.904209 -10.869045  0.492273
balance      0.005282   0.006191   0.005737  0.000232
income     -13.043675  19.110575   3.033450  8.202766
studentYes  -1.109831  -0.183721  -0.646776  0.236257


In [27]:
conf99 = pd.DataFrame()
conf99['0.5%'] = fit3.params + stats.norm.ppf(0.005)*fit3.bse
conf99['99.5%'] = fit3.params + stats.norm.ppf(0.995)*fit3.bse
print(conf99)

                 0.5%      99.5%
Intercept  -12.137056  -9.601035
balance      0.005139   0.006334
income     -18.095474  24.162374
studentYes  -1.255333  -0.038218


In [34]:
from sklearn.metrics import confusion_matrix

In [29]:
type(dft["defaultYes"])

pandas.core.series.Series

In [30]:
dft["defaultYes"].value_counts()

0    9667
1     333
Name: defaultYes, dtype: int64

In [31]:
pred_p = fit2.predict()   
pred_c1 = [ 1 if x > 0.5 else 0 for x in pred_p]
print(confusion_matrix(dft["defaultYes"], pred_c1))  

[[9625   42]
 [ 233  100]]


In [32]:
pred_c2 = [ 1 if x > 0.02 else 0 for x in pred_p]
print(confusion_matrix(dft["defaultYes"], pred_c2))

[[7864 1803]
 [  22  311]]


# Bankrupt data

In [5]:
import statsmodels.api as sm                                                                                 #통계모형  
import statsmodels.formula.api as smf

In [6]:
bank = pd.read_table('../data/bankrupt.txt', sep="\s+")  #하나 이상의 스페이스 sep="\s+"
bank.head()

x1    x2    x3    x4  y
0 -0.45 -0.41  1.09  0.45  0
1 -0.56 -0.31  1.51  0.16  0
2  0.06  0.02  1.01  0.40  0
3 -0.07 -0.09  1.45  0.26  0
4 -0.10 -0.09  1.56  0.67  0

In [7]:
fm2=smf.glm(formula = 'y ~ x1 + x2 + x3 + x4', 
           data=bank, family=sm.families.Binomial()).fit()
fm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                   46
Model:                            GLM   Df Residuals:                       41
Model Family:                Binomial   Df Model:                            4
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -13.722
Date:                Mon, 29 Mar 2021   Deviance:                       27.443
Time:                        12:14:34   Pearson chi2:                     54.1
No. Iterations:                     7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.3195      2.366     -2.248      0.025      -9.958      -0.681
x1             7.1378      6.002      1.189      0.234      -4.625      18.901
x2            -3.7033     13.670     -0.271      0.786     -30.497      23.090
x3             3.4148      1.204      2.837      0.005       1.056       5.774
x4            -2.9684      3.065     -0.968      0.333      -8.976       3.040
==============================================================================
"""

In [8]:
print(fm2.df_model)
print(-2*fm2.llf + 2*(fm2.df_model+1)) # 여기서는 df_model = (모수의 갯수 - 1(보통 상수항)) 로 정의
print(fm2.aic)

4
37.44323448446937
37.44323448446937


In [10]:
print(-2*fm2.llf + np.log(fm2.nobs)*(fm2.df_model+1)) # 여기서는 df_model = (모수의 갯수-1(보통 상수항)) 로 정의
print(fm2.bic_llf)

46.58644146691485
46.58644146691485


In [11]:
p=fm2.predict()
y=bank["y"]
print(sum(y*np.log(p)+(1-y)*np.log(1-p)))                # loglikelihood
print(fm2.llf)                                           # loglikelihood

-13.721617242234684
-13.721617242234684


## Model Selection: Forward (by hand)
> 전진탐색

In [39]:
smf.glm('y~1', data=bank,
        family=sm.families.Binomial()).fit().aic

65.42127484920293

In [40]:
smf.glm('y~x1', data=bank,
        family=sm.families.Binomial()).fit().aic

47.6502469534637

In [41]:
smf.glm('y~x2', data=bank,
        family=sm.families.Binomial()).fit().aic

47.85715656400864

In [42]:
smf.glm('y~x3', data=bank,
        family=sm.families.Binomial()).fit().aic

39.34399025597335

In [43]:
smf.glm('y~x4', data=bank,
        family=sm.families.Binomial()).fit().aic

67.38101453637978

In [44]:
smf.glm('y~x3', data=bank,
        family=sm.families.Binomial()).fit().aic

39.34399025597335

In [45]:
smf.glm('y~x3+x1', data=bank,
        family=sm.families.Binomial()).fit().aic

34.63561349297248

In [46]:
smf.glm('y~x3+x2', data=bank,
        family=sm.families.Binomial()).fit().aic

36.82850016937259

In [47]:
smf.glm('y~x3+x4', data=bank,
        family=sm.families.Binomial()).fit().aic

38.764372136654615

In [48]:
smf.glm('y~x3+x1+x2', data=bank,
        family=sm.families.Binomial()).fit().aic

36.514336009819885

In [49]:
smf.glm('y~x3+x1+x4', data=bank,
        family=sm.families.Binomial()).fit().aic

35.516314435067855

## [F] forward_logistic_aic 함수 만들기

In [50]:
X=bank.iloc[:,0:4]                       #dataframe
y=bank.iloc[:,4].astype(np.int)
X.head()
#y.head()

/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


x1    x2    x3    x4
0 -0.45 -0.41  1.09  0.45
1 -0.56 -0.31  1.51  0.16
2  0.06  0.02  1.01  0.40
3 -0.07 -0.09  1.45  0.26
4 -0.10 -0.09  1.56  0.67

In [51]:
#%%%% forward
def forward_logistic_aic(data, X, y, verbose=True):
    add_list=list(X.columns)
    included = []
    while True:
        changed=False
        
        if included:
            formula = 'y~{}'.format('+'.join(included))
        else:
            formula = 'y~1'
        model = smf.glm(formula, data, family=sm.families.Binomial()).fit()
        
        aic = {}
        aic['none'] = model.aic
        
        print('Step : AIC =',aic['none'].round(3))
        print(formula)
    
        for add in add_list:
            remain = included + [add]
            formula = 'y~{}'.format('+'.join(remain))
            model = smf.glm(formula, data, family=sm.families.Binomial()).fit()
            aic[add] = model.aic
        aic_sort = sorted(aic.items(), key=lambda x:x[1])
        
        print('\t AIC')
        for item, key in aic_sort:
            if(item=='none'):
                print('<',item,'>','\t ',key.round(3),sep='')
            else:
                print('+',item,'\t',key.round(3))
        
        #display(aic_sort)
        aic_min = aic_sort[0][1]
        if aic_min < aic['none']:
            changed=True
            best_feature = aic_sort[0][0]
            included.append(best_feature)
            add_list.remove(best_feature)
            if verbose:
                print('>> Add {} with AIC {} \n'.format(best_feature, aic_min.round(3)))
        if not changed:
            break
    return included



In [52]:
forward_logistic_aic(bank, X, y)

Step : AIC = 65.421
y~1
	 AIC
+ x3 	 39.344
+ x1 	 47.65
+ x2 	 47.857
<none>	 65.421
+ x4 	 67.381
>> Add x3 with AIC 39.344 

Step : AIC = 39.344
y~x3
	 AIC
+ x1 	 34.636
+ x2 	 36.829
+ x4 	 38.764
<none>	 39.344
>> Add x1 with AIC 34.636 

Step : AIC = 34.636
y~x3+x1
	 AIC
<none>	 34.636
+ x4 	 35.516
+ x2 	 36.514


['x3', 'x1']

## [B] backward_logistic_aic 함수 만들기

In [53]:
#%%%% backward
def backward_logistic_aic(data, X, y, verbose=True):
    included=list(X.columns)
    while True:
        changed=False
        formula = 'y~{}'.format('+'.join(included))
        model = smf.glm(formula, data, family=sm.families.Binomial()).fit()
        aic = {}
        aic['none'] = model.aic
        
        print('Step : AIC =',aic['none'].round(3))
        print(formula)
    
        for drop in included:
            remain = list(set(included)-set([drop]))
            formula = 'y~{}'.format('+'.join(remain))
            model = smf.glm(formula, data, family=sm.families.Binomial()).fit()
            aic[drop] = model.aic
        aic_sort = sorted(aic.items(), key=lambda x:x[1])
        
        
        print('\t AIC')
        for item, key in aic_sort:
            if(item=='none'):
                print('<',item,'>','\t ',key.round(3),sep='')
            else:
                print('-',item,'\t',key.round(3))
        
        #display(aic_sort)
        aic_min = aic_sort[0][1]
        if aic_min < aic['none']:
            changed=True
            worst_feature = aic_sort[0][0]
            included.remove(worst_feature)
            if verbose:
                print('>> Drop {} with AIC {} \n'.format(worst_feature, aic_min.round(3)))
        if not changed:
            break
    return included



In [54]:
backward_logistic_aic(bank, X, y)

Step : AIC = 37.443
y~x1+x2+x3+x4
	 AIC
- x2 	 35.516
- x4 	 36.514
- x1 	 37.133
<none>	 37.443
- x3 	 50.56
>> Drop x2 with AIC 35.516 

Step : AIC = 35.516
y~x1+x3+x4
	 AIC
- x4 	 34.636
<none>	 35.516
- x1 	 38.764
- x3 	 49.624
>> Drop x4 with AIC 34.636 

Step : AIC = 34.636
y~x1+x3
	 AIC
<none>	 34.636
- x1 	 39.344
- x3 	 47.65


['x1', 'x3']

## [S] stepwise_logistic_aic 함수 만들기

In [40]:
def stepwise_logistic_aic_scope(data, X, y, 
                                start=[], upper=[], lower=[], 
                                verbose=True):
    
    add_list = X.columns
    
    
    if not start:
        start = list(X.columns)    
    if not upper:
        upper = list(X.columns)
   
    included = start[:]
    add_list = [x for x in add_list if x not in included]
    
    while True:
        changed=False
        
        if included:
            formula = 'y~{}'.format('+'.join(included))
        else:
            formula = 'y~1'
            
        model = smf.glm(formula, data,family=sm.families.Binomial()).fit()
        
        aic = {}
        aic['none'] = model.aic
        
        print('Step : AIC =',aic['none'].round(3))
        print(formula)
        
    
        for drop in included:
            remain = [x for x in included if x not in [drop]]
            if remain:
                formula = 'y~{}'.format('+'.join(remain))
            else:
                formula = 'y~1'
            model = smf.glm(formula, data, family=sm.families.Binomial()).fit()
            aic[drop] = model.aic
                
        for add in add_list:
            remain = included + [add]
            formula = 'y~{}'.format('+'.join(remain))
            model = smf.glm(formula, data, family=sm.families.Binomial()).fit()
            aic[add] = model.aic
        
        aic_sort = sorted(aic.items(), key=lambda x:x[1])
        
        print('\t AIC')
        for item, key in aic_sort:
            if(item=='none'):
                print('<',item,'>','\t ',key.round(3),sep='')
            else:
                if pd.Series(item).isin(included).bool():
                    print('-',item,'\t',key.round(3))
                else:
                    print('+',item,'\t',key.round(3))
                    
        
        #display(aic_sort)
        aic_min = aic_sort[0][1]
        if aic_min < aic['none']:
            changed=True
            ch_feature = aic_sort[0][0]
            if pd.Series(ch_feature).isin(included).bool():
                included.remove(ch_feature)
                add_list.append(ch_feature) 
                if verbose:
                    print('>> Drop {} with AIC {} \n'.format(ch_feature, aic_min.round(3)))
            else:
                included.append(ch_feature)
                add_list.remove(ch_feature)
                if verbose:
                    print('>> Add {} with AIC {} \n'.format(ch_feature, aic_min.round(3)))
            
        if (not changed) | (set(included)==set(upper)) | (set(included)==set(lower)):
            if included:
                formula = 'y~{}'.format('+'.join(included))
            else:
                formula = 'y~1'

            model = smf.glm(formula, data,family=sm.families.Binomial()).fit()
            print('\n')
            print(model.summary2())
            break
    return included

In [41]:
stepwise_logistic_aic_scope(bank,X,y, 
                            start=['x2'], upper=['x1','x2','x3','x4'], lower=[])

Step : AIC = 47.857
y~x2
	 AIC
+ x3 	 36.829
<none>	 47.857
+ x1 	 48.56
+ x4 	 49.767
- x2 	 65.421
>> Add x3 with AIC 36.829 

Step : AIC = 36.829
y~x2+x3
	 AIC
+ x1 	 36.514
<none>	 36.829
+ x4 	 37.133
- x2 	 39.344
- x3 	 47.857
>> Add x1 with AIC 36.514 

Step : AIC = 36.514
y~x2+x3+x1
	 AIC
- x2 	 34.636
<none>	 36.514
- x1 	 36.829
+ x4 	 37.443
- x3 	 48.56
>> Drop x2 with AIC 34.636 

Step : AIC = 34.636
y~x3+x1
	 AIC
<none>	 34.636
+ x4 	 35.516
+ x2 	 36.514
- x1 	 39.344
- x3 	 47.65


              Results: Generalized linear model
Model:              GLM              AIC:            34.6356  
Link Function:      logit            BIC:            -135.9960
Dependent Variable: y                Log-Likelihood: -14.318  
Date:               2021-03-03 21:19 LL-Null:        -31.711  
No. Observations:   46               Deviance:       28.636   
Df Model:           2                Pearson chi2:   60.8     
Df Residuals:       43               Scale:          1.0000   
Method:

['x3', 'x1']

# 데이터 분할 및 교차검증

In [12]:
fm0=smf.glm(formula = 'y ~ 1', 
           data=bank, family=sm.families.Binomial()).fit()
(fm2.llf-fm0.llf)*2, -fm2.llf*2

(35.97804036473356, 27.443234484469368)

In [14]:
from sklearn.model_selection import train_test_split

bank_train, bank_test = train_test_split(bank, test_size=0.3, random_state=10) #random_state 를 특정값으로 고정해야함 옵션이 없으면 시행마다 다른 숫자
bank.shape, bank_train.shape, bank_test.shape

((46, 5), (32, 5), (14, 5))

In [15]:
fm2_tr=smf.glm(formula = 'y ~ x1 + x2 + x3 + x4', 
           data=bank_train, family=sm.families.Binomial()).fit()
p=fm2_tr.predict(bank_test)
yte=bank_test["y"]
-sum(yte*np.log(p)+(1-yte)*np.log(1-p))   # -loglikelihood on test set

3.4236317835278336

In [45]:
fm1_tr=smf.glm(formula = 'y ~ x1 + x3 ', 
           data=bank_train, family=sm.families.Binomial()).fit()
p=fm1_tr.predict(bank_test)
yte=bank_test["y"]
-sum(yte*np.log(p)+(1-yte)*np.log(1-p))   # -loglikelihood on test set

2.9753865555360206

# K - fold 를 이용한 검증
- 훈련데이터로 두 모형 적합
- 실험데이터에 대한 적합도 측정

In [46]:
from sklearn.model_selection import KFold

scores1 = np.zeros(5)
scores2 = np.zeros(5)
cv = KFold(5, shuffle=True, random_state=0)

for i, (idx_train, idx_test) in enumerate(cv.split(bank)):
    bank_train = bank.iloc[idx_train]
    bank_test = bank.iloc[idx_test]
    
    yte=bank_test["y"]

    fm1_tr=smf.glm(formula = 'y ~ x1 + x3 ', 
           data=bank_train, family=sm.families.Binomial()).fit()
    fm2_tr=smf.glm(formula = 'y ~ x1 + x2 + x3 + x4', 
           data=bank_train, family=sm.families.Binomial()).fit()
    
    p=fm1_tr.predict(bank_test)
    scores1[i] = -(yte*np.log(p)+(1-yte)*np.log(1-p)).sum()   

    p=fm2_tr.predict(bank_test)
    scores2[i] = -(yte*np.log(p)+(1-yte)*np.log(1-p)).sum()

scores1.mean(), scores2.mean()

(5.520810647011532, 7.206015359368315)

# sklearn에서 로지스틱회귀분석
##### Note: The intercept is regularized in sklearn but not in R. The option penalty='none' is not supported for the liblinear solver

In [47]:
from sklearn.linear_model import LogisticRegression 

In [48]:
X=bank.values[:,:4]
y=bank.values[:,4]
# 또는 
#X = bank.loc[:,'x1':'x4']
#y = bank['y']
log_reg=LogisticRegression(penalty='none')    
fit1=log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-5.31951669]
[[ 7.13779753 -3.70328691  3.4148359  -2.96838772]]


In [49]:
X=bank.values[:,:4]
y=bank.values[:,4]
# 또는 
#X = bank.loc[:,'x1':'x4']
#y = bank['y']
log_reg=LogisticRegression(solver='newton-cg', penalty='none')    
fit1=log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-5.31951257]
[[ 7.13780424 -3.70332948  3.41483434 -2.96839048]]


In [50]:
X=bank.values[:,:4]
y=bank.values[:,4]
# 또는 
#X = bank.loc[:,'x1':'x4']
#y = bank['y']
log_reg=LogisticRegression(solver='sag', penalty='none')    
fit1=log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-4.73999853]
[[ 4.64735608  1.75824501  3.16070785 -2.98478736]]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "


In [51]:
dir(fm2)
fm2.params

Intercept   -5.319513
x1           7.137804
x2          -3.703330
x3           3.414834
x4          -2.968390
dtype: float64

# 예제: iris data

In [16]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [17]:
iris["data"]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [18]:
iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
X = iris['data'][:,2:]                    # 오른쪽 두 컬럼 
y = (iris['target']==2).astype(np.int)    # T/F를 0/1로 변환

/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [20]:
from sklearn.linear_model import LogisticRegression                     #싸이킷런: 머신러닝도구
log_reg=LogisticRegression(solver='newton-cg', penalty="none")
fit1=log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-45.27188876]
[[ 5.75446795 10.44661558]]


In [21]:
from sklearn.linear_model import LogisticRegression                     #싸이킷런: 머신러닝도구
log_reg=LogisticRegression()
fit2=log_reg.fit(X,y)
print(fit2.intercept_)
print(fit2.coef_)

[-17.5481106]
[[2.77762524 2.38552012]]


In [22]:
data=pd.DataFrame(np.c_[X,y],columns=['x1','x2','y'])

In [23]:
m3 = smf.glm(formula = 'y~x1+x2',data=data,family=sm.families.Binomial())
fit3 = m3.fit()
fit3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                  150
Model:                            GLM   Df Residuals:                      147
Model Family:                Binomial   Df Model:                            2
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -10.282
Date:                Mon, 29 Mar 2021   Deviance:                       20.564
Time:                        12:33:58   Pearson chi2:                     20.1
No. Iterations:                    10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -45.2723     13.611     -3.326      0.001     -71.950     -18.594
x1             5.7545      2.306      2.496      0.013       1.235      10.274
x2            10.4467      3.756      2.782      0.005       3.086      17.808
==============================================================================
"""

# 다항 로지스틱 회귀모형

In [24]:
import statsmodels.formula.api as smf
X = iris['data'][:,(2,3)]                     
y = iris['target']
data=pd.DataFrame(np.c_[X,y],columns=['x1','x2','y'])
fit_mn1 = smf.mnlogit(formula='y~x1+x2',data=data).fit(method='ncg')
print(fit_mn1.summary())

         Current function value: 0.068555
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
         Hessian evaluations: 35
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      144
Method:                           MLE   Df Model:                            4
Date:                Mon, 29 Mar 2021   Pseudo R-squ.:                  0.9376
Time:                        12:34:00   Log-Likelihood:                -10.283
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 1.229e-65
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -27.2178     90.934     -0.299

/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [25]:
fit_mn1.mle_retvals

{'fopt': 0.06855457926002029,
 'fcalls': 36,
 'gcalls': 36,
 'hcalls': 35,
 'warnflag': 1,
 'converged': False}

In [26]:
import statsmodels.formula.api as smf
X = iris['data'][:,(2,3)]                     
y = iris['target']
data=pd.DataFrame(np.c_[X,y],columns=['x1','x2','y'])
fit_mn1 = smf.mnlogit(formula='y~x2',data=data).fit(method='ncg')
print(fit_mn1.summary())

         Current function value: 0.111439
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
         Hessian evaluations: 35
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      146
Method:                           MLE   Df Model:                            2
Date:                Mon, 29 Mar 2021   Pseudo R-squ.:                  0.8986
Time:                        12:34:02   Log-Likelihood:                -16.716
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 4.914e-65
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -26.5489     53.603     -0.495

/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [27]:
import statsmodels.api as sm

X = iris['data'][:,(2,3)]                     
X = sm.add_constant(X)
y = iris['target']

fit_mn1a = sm.MNLogit(y, X).fit(method='ncg')
print(fit_mn1a.summary())

         Current function value: 0.068555
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
         Hessian evaluations: 35
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      144
Method:                           MLE   Df Model:                            4
Date:                Mon, 29 Mar 2021   Pseudo R-squ.:                  0.9376
Time:                        12:34:03   Log-Likelihood:                -10.283
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 1.229e-65
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -27.2178     90.934     -0.299

/Users/hmp/opt/anaconda3/envs/yonsei/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [28]:
from sklearn.linear_model import LogisticRegression 
X = iris['data'][:,(2,3)]                            # 오른쪽 두 컬럼 
y = iris['target']
fit_mn2=LogisticRegression(multi_class='multinomial',solver ='newton-cg',penalty='none').fit(X,y)
print(fit_mn2.intercept_.round(4))
print(fit_mn2.coef_.round(4))

[ 36.9463   4.163  -41.1093]
[[ -7.9636 -12.7065]
 [  1.1045   1.1299]
 [  6.8591  11.5766]]


In [29]:
fit_mn1a.predict([[1,5,2]]).round(5)

array([[0.    , 0.0122, 0.9878]])

In [30]:
fit_mn1a.predict([[1,2.5,1]]).round(5)

array([[0.03556, 0.96444, 0.     ]])

In [31]:
fit_mn2.predict_proba([[5,2]]).round(5)

array([[0.    , 0.0122, 0.9878]])

In [32]:
fit_mn2.predict_proba([[2.5,1]]).round(5)

array([[0.02358, 0.97642, 0.     ]])

In [35]:
pred1=fit_mn1.predict().argmax(1)
print(confusion_matrix(y, pred1))

[[50  0  0]
 [ 0 48  2]
 [ 0  4 46]]
