<a href="https://colab.research.google.com/github/pyohamen/yonsei/blob/master/2-1_%EC%9D%98%EC%82%AC%EA%B2%B0%EC%A0%95%EB%82%98%EB%AC%B4_%EB%B0%8F_%EB%AA%A8%ED%98%95%EB%B9%84%EA%B5%90/Code20_%EB%B6%84%EB%A5%98%EB%AA%A8%ED%98%95%EB%B9%84%EA%B5%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loan 데이터 분류모형 예측성능 비교

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('loan.csv')

In [ ]:
df['job'] = df['job'].replace({'Office':0, 'ProfExe':1, 'Other':2, 'Mgr':3, 'Self':4, 'Sales':5})

In [ ]:
X = df.drop(['y'], axis=1)
y = df['y']
xname = X.columns
yname = ['Normal','Bad']

## Train/Test 데이터 분할

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0, stratify=y)

## 로지스틱 회귀분석

In [ ]:
from sklearn.linear_model import LogisticRegression
# max_iter: 과도한 수행을 방지
m1 = LogisticRegression(random_state=0, max_iter = 1000)
m1.fit(X_train, y_train)
# 확률 예측
m1_prob = m1.predict_proba(X_test)
pd.DataFrame(m1_prob)

0         1
0     0.797334  0.202666
1     0.772756  0.227244
2     0.765714  0.234286
3     0.756511  0.243489
4     0.642193  0.357807
...        ...       ...
2792  0.551095  0.448905
2793  0.740449  0.259551
2794  0.485864  0.514136
2795  0.413873  0.586127
2796  0.590092  0.409908

[2797 rows x 2 columns]

### cut-off=0.1

In [ ]:
threshold = 0.1
m1_pred = (m1_prob[:,1]>threshold).astype(int)
m1_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
# m1 의 confusion matrix
m1_cm = confusion_matrix(y_test, m1_pred)
pd.DataFrame(m1_cm)

0     1
0  426  1695
1   45   631

In [ ]:
# 정확도
accu1 = np.trace(m1_cm)/len(y_test)
print('정확도    :', np.round(accu1,2))

# 특이도, 민감도
spec1, sens1 = np.diag(m1_cm) / np.sum(m1_cm, axis = 1)
print('특이도    :', np.round(spec1,2))
print('민감도    :', np.round(sens1,2))

# 정밀도
prec1 = m1_cm[1,1] / np.sum(m1_cm, axis=0)[1]
print('정밀도    :', np.round(prec1,2))

# F1-score
f1_1 = 2*prec1*sens1 / (prec1+sens1)
print('F1-score :', np.round(f1_1,2))

정확도    : 0.38
특이도    : 0.2
민감도    : 0.93
정밀도    : 0.27
F1-score : 0.42


### cut-off=0.3

In [ ]:
threshold = 0.3
m1_pred = (m1_prob[:,1]>threshold).astype(int)
m1_pred

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
m1_cm = confusion_matrix(y_test, m1_pred)
pd.DataFrame(m1_cm)

0    1
0  1583  538
1   233  443

In [ ]:
# 정확도
accu1 = np.trace(m1_cm)/len(y_test)
print('정확도 :', np.round(accu1,2))

# 특이도, 민감도
spec1, sens1 = np.diag(m1_cm) / np.sum(m1_cm, axis = 1)
print('특이도 :', np.round(spec1,2))
print('민감도 :', np.round(sens1,2))

# 정밀도
prec1 = m1_cm[1,1] / np.sum(m1_cm, axis=0)[1]
print('정밀도 :', np.round(prec1,2))

# F1-score
f1_1 = 2*prec1*sens1 / (prec1+sens1)
print('F1-score :', np.round(f1_1,2))

정확도 : 0.72
특이도 : 0.75
민감도 : 0.66
정밀도 : 0.45
F1-score : 0.53


### cut-off=0.5

In [ ]:
threshold = 0.5
m1_pred = (m1_prob[:,1]>threshold).astype(int)
m1_pred

array([0, 0, 0, ..., 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
m1_cm = confusion_matrix(y_test, m1_pred)
pd.DataFrame(m1_cm)

0    1
0  2003  118
1   520  156

In [ ]:
# 정확도
accu1 = np.trace(m1_cm)/len(y_test)
print('정확도 :', np.round(accu1,2))

# 특이도, 민감도
spec1, sens1 = np.diag(m1_cm) / np.sum(m1_cm, axis = 1)
print('특이도 :', np.round(spec1,2))
print('민감도 :', np.round(sens1,2))

# 정밀도
prec1 = m1_cm[1,1] / np.sum(m1_cm, axis=0)[1]
print('정밀도 :', np.round(prec1,2))

# F1-score
f1_1 = 2*prec1*sens1 / (prec1+sens1)
print('F1-score :', np.round(f1_1,2))

정확도 : 0.77
특이도 : 0.94
민감도 : 0.23
정밀도 : 0.57
F1-score : 0.33
